@startuml SQ2_SignUp

skin rose
scale 3
hide footbox

actor "User" as user
boundary "User Interface" as ui
control "Authenciation Controller" as aCon
entity "Authenciation Service" as aSer
entity "Account Reposotory" as aRepo
database "Database" as db

autonumber
user++
user -> ui++ : Access sign up page
ui -> user : Display sign up page
user -> ui : Enter account info\nand click "Sign Up" button
ui -> aCon++ : Send sign up request\nand account info
aCon -> aSer++ : Send sign up request\nand account info
aSer -> aSer : Check account info
alt account info is invalid
    aSer -> aCon : Return error message
    aCon -> ui : Return error message
    ui -> user : Display error message
else account info is valid
    autonumber 7
    aSer -> aRepo++ : Create new account
    aRepo -> db++ : Query inser account info
    db -> aRepo-- : Return success message
    aRepo -> aSer-- : Return success message
    aSer -> aCon-- : Return success message
    aCon -> ui-- : Return success message
    ui -> user-- : Display home page
end
user--
@enduml