@startuml SQ3_ViewOrderList

skin rose
scale 3
hide footbox

actor "User" as user
boundary "User Interface" as ui
control "Order Controller" as aCon
entity "Order Service" as aSer

autonumber
user++
user -> ui++ : Access order page
ui -> aCon++ : Request order list info
aCon -> aSer++ : Request order list info
aSer -> aSer : Get order list info
aSer -> aCon-- : Return order list info
aCon -> ui-- : Return order list info
ui -> user-- : Display order page
user--
@enduml