@startuml SQ8_Compareproduct

skin rose
scale 3
hide footbox

actor "User" as user
boundary "User Interface" as ui
control "Product Controller" as pCon
entity "Product Service" as pSer

autonumber
user++
user -> ui++ : Access detail product page
ui -> pCon++ : Request detail product info
ui -> pCon : Request list compare product
pCon -> pSer++ : Request detail product info
pCon -> pSer : Request list compare product
pSer -> pSer : Get detail product info
pSer -> pSer : Get list compare product info
pSer -> pCon : Return detail product info
pSer -> pCon-- : Return list compare product info
pCon -> ui : Return detail product info
pCon -> ui-- : Return list compare product info
ui -> user-- : Display detail product info
user--
@enduml